### PR TITLE
Architectural Candy

### PR DESCRIPTION
**Pull request by toddpi314**
Rules to follow once you are preparing for a NodeJS release:
- Lock down versions
- Clearly separate App and Dev dependencies 
- Remove unused modules

Pro-Top: add 'save-exact=true' to ~/.npmrc to assure you always are working with exact versions of an npm module

### CODE REVIEW

**Comment by toddpi314** [comment]
In this PR, I focused on a few important architecture features:
- clearly separate tests from application source - Tests should not be deployed and should easily be 'excluded' from distributions - see the `/src/test` folder
- clearly separate `server` and `client` code - This will help developers identify what is running in the browser and what is running on the server. see the `/src/client` folder
- added nconf usage to help with mutli-environmental testing
- Fixed `gulp watch` task

**Comment by toddpi314** [comment]
Updates to how the index.html is served:
- In prior setup, the Index.html was being dropped down as a static resource upon root GET verb
- In new setup, this has been changed to ExpressJS serving up the `src/view/index.html` using the `html` view engine. Additionally, I added support for `ejs` to allow you guys to do ninja class server-side conditions in the initially rendered page.

**Comment by toddpi314** [comment]
Added Ninja-class Unit Test support.

Tests now run over three major areas (see `src/test`):
- Client Unit Test - using Karma on the AngularJS components (these are the tests you wrote David)
- Server Unit Tests - using Mocha on NodeJS components (using SuperTest, which is a request/response automation suite that plugs into NodeJS runtime)
- Integration Tests - using WebDriver (Selinium) to test actual app usage on a live website

Integration Tests using `WebDriver` are wicked. It launches the web app in node, opens a real web browser and lets you use the `Protractor` api to interact with the Web UI. (see http://angular.github.io/protractor/#/tutorial)

It is recommended that when you find a bug, just write a real-world Protractor Integration test to reproduce the use-case consistently. Write the test so that you assert the desired result and it fails. Then, jump into the actual app and dev until your test is green!

New Grunt targets were added to allow interaction with the enhanced test suite:`gulp test-client`, `gulp test-server`, `gulp test-integration`. `gulp-test` just runs them all, with Integration tests last (no point in taking the plane for a spin if the wing is missing).

**Comment by davidcrosby** [comment]
Wow, this is amazing. Thank you very much, Todd.

All of the architectural changes and gulp setup will make writing the tests
and improving the quality of the app exponentially easier for me.

I tried to clone it from your repo to test the changes and poke around,
when I run `gulp server-start` I get an error that it cannot find the
module ejs, do you know what might be causing this? I think I'll just post
the stack trace.

Again, thanks a bunch.

`connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for
alternatives
connect.limit() will be removed in connect 3.0

module.js:340
throw err;
^
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Function.app.use.res.json.error
(/Users/David/code/todd_pinch/src/app.js:23:24)
    at Function.app.configure
(/Users/David/code/todd_pinch/node_modules/express/lib/application.js:391:61)
    at Object.<anonymous> (/Users/David/code/todd_pinch/src/app.js:10:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)`

**Comment by davidcrosby** [comment]
Gmail is being weird and put my email in the hidden pane. Sorry for spam.

Wow, this is amazing. Thank you very much, Todd.

All of the architectural changes and gulp setup will make writing the tests
and improving the quality of the app exponentially easier for me.

I tried to clone it from your repo to test the changes and poke around,
when I run `gulp server-start` I get an error that it cannot find the
module ejs, do you know what might be causing this? I think I'll just post
the stack trace.

Again, thanks a bunch.

`connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for
alternatives
connect.limit() will be removed in connect 3.0

module.js:340
throw err;
^
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Function.app.use.res.json.error
(/Users/David/code/todd_pinch/src/app.js:23:24)
    at Function.app.configure
(/Users/David/code/todd_pinch/node_modules/express/lib/application.js:391:61)
    at Object.<anonymous> (/Users/David/code/todd_pinch/src/app.js:10:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)`

**Comment by davidcrosby** [comment]
It might be having an ejs error because I cloned the your fork of the repo, it's passing the Travis CI build, so I'm just going to merge it and see if there's still an error.

**Comment by davidcrosby** [comment]
Oh, silly me. ejs wasn't in the package.json, all good now!

**Pull request merged**
